"""Arreglar cosas5

Revision ID: 7c5c9a1020a9
Revises: 83d6b5940ee1
Create Date: 2026-03-09 21:05:08.808113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c5c9a1020a9'
down_revision = '83d6b5940ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'maestros', ['maestro_id'], ['matricula'])

    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'alumnos', ['alumno_id'], ['id'])
        batch_op.create_foreign_key(None, 'cursos', ['curso_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
