"""Arreglar cosas4

Revision ID: 83d6b5940ee1
Revises: e95df113c69a
Create Date: 2026-03-09 21:03:03.058818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83d6b5940ee1'
down_revision = 'e95df113c69a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incripciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_alumno_curso'))

    op.drop_table('incripciones')
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'maestros', ['maestro_id'], ['matricula'])

    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'alumnos', ['alumno_id'], ['id'])
        batch_op.create_foreign_key(None, 'cursos', ['curso_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscripciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('incripciones',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('alumno_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('curso_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_inscripcion', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    with op.batch_alter_table('incripciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_alumno_curso'), ['alumno_id', 'curso_id'], unique=True)

    # ### end Alembic commands ###
