"""Agregar Cursos e inscripciones

Revision ID: cc8618370699
Revises: b59b0bf9f375
Create Date: 2026-03-09 20:41:57.775869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc8618370699'
down_revision = 'b59b0bf9f375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'maestros', ['maestro_id'], ['matricula'])

    with op.batch_alter_table('incripciones', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'alumnos', ['alumno_id'], ['id'])
        batch_op.create_foreign_key(None, 'cursos', ['curso_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incripciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
