"""Arreglar cosas3

Revision ID: e95df113c69a
Revises: 689617864ebe
Create Date: 2026-03-09 21:00:31.633057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95df113c69a'
down_revision = '689617864ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'maestros', ['maestro_id'], ['matricula'])

    with op.batch_alter_table('incripciones', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'cursos', ['curso_id'], ['id'])
        batch_op.create_foreign_key(None, 'alumnos', ['alumno_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incripciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
